repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      additional_dependencies: [mccabe]
      args: ["--max-line-length", "88", "--max-complexity", "10", "--ignore=E203"]

  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      exclude: tests
      types: [python]

  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: mypy
      language: system
      exclude: tests
      types: [python]
      args: ["--strict"]
